name: Release Linux package

on:
  push:
    tags:
        - v*

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U pyinstaller

      - name: Build package
        run: pyinstaller download.py

      - name: Release package
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          makeLatest: true
          generateReleaseNotes: true